--delete from humorously_joke;
insert all
    into humorously_joke (ID, CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (1,'09-DEC-19 01.21.29.167122000 AM','Why did the Chicken Cross the Road?','"Why did the Chicken Cross the Road? To get to the other Side!"',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (21,'09-DEC-19 02.51.07.850044000 AM','Garage Dog','I held a garage sale with my little blond cairn terrier for company. Soon came the first customer. He took his time browsing and examining everything I had out for sale. Eventually, he found something that interested him. “Excuse me,” he said. “How much for the dog?”',21,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (41,'10-DEC-19 12.52.44.112151000 AM','Serious Homework','My 11-year-old takes his homework seriously. One question required him to write a sentence using the word version. His sentence: “Have you heard of the version Mary?”',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (61,'10-DEC-19 01.03.12.583514000 AM','What''s the Best thing about Switzerland?','"What''s the Best thing about Switzerland? I don''t know, but the flag is a big plus!"',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (43,'10-DEC-19 12.58.31.224701000 AM','NO OYSTERS FOR ME','One day, my physician father treated himself to a plate of raw oysters and offered to share them with me. Just as I was about to dig in, he picked up an oyster, examined it, and commented, “They remind me of infected tonsils.”And that’s the story of how he ended up eating the entire plate of oysters himself.',21,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (81,'10-DEC-19 03.08.07.847225000 AM','LAZY KANGAROO,','"Q: What do you call a lazy baby kangaroo?  A: A pouch potato."',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (101,'12-DEC-19 12.35.12.043468000 AM','GEORGE WASHINGTON THE INVENTOR','Our eight-year-old daughter: “Are you saying that George Washington didn’t invent the toilet?”',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (121,'12-DEC-19 04.42.18.040960000 AM','NO COMMAS','My three favorite things are eating my family and not using commas.',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (122,'12-DEC-19 04.43.21.208352000 AM','NO LAUGHS IN THE FUTURE','I was gonna tell a time-traveling joke, but you guys didn’t like it.',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (183,'15-DEC-19 06.32.04.750305000 PM','Riddle:  Say what?','"I speak without a mouth and hear without ears.  I have not body, but come alive with wind.  What am I? An echo."',21,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (141,'12-DEC-19 04.55.24.934194000 AM','I invented a new word!','"I invented a new word!  Plagiarism!"',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (161,'12-DEC-19 06.45.20.498523000 AM','Did you hear about the mathematician who''s afraid','"Did you hear about the mathematician who’s afraid of negative numbers?  He''ll stop at nothing to avoid them."',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (72,'10-DEC-19 01.57.59.952078000 AM','TELEPATHETIC','My wife keeps telling everyone that she can read their minds, but she never can. She’s telepathetic.',1,1 )
    into humorously_joke (ID,CREATED, TITLE, TEXT, CATEGORY_ID, USER_ID )
    values (77,'10-DEC-19 02.04.05.124392000 AM','TAKING THE BULL’S PILLS','"An elderly farmer had an old bull that lost its usual desire and no longer went near the cows. The farmer called the vet, who prescribed a pill to stimulate the bull’s interest. A few weeks later, the farmer ran into a friend, who asked, “How’s that bull?”  “Great!” said the farmer. “The bull is back to his former frisky self.”  “That’s fantastic. What miracle drug did the vet prescribe?”  “I don’t know,” said the farmer. “But it tastes like licorice.”"',1,1 )
select 1 from dual;
    commit