create table journal (
    "ID" number(11,0) generated by default on null
        as identity minvalue 1 maxvalue 9999999999999999999999999999
        increment by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable,
    "ENTITY_ID" number(11,0),
    "ENTITY_NAME" nvarchar2(200),
    "ENTITY_DESC" nvarchar2(200),
    "CREATED" timestamp (6) not null enable,
    primary key ("ID")
    using index pctfree 10 initrans 2 maxtrans 255 compute statistics
 storage(initial 65536 next 1048576 minextents 1 maxextents 2147483645
 pctincrease 0 freelists 1 freelist groups 1
 buffer_pool default flash_cache default cell_flash_cache default)
 TABLESPACE "SYSTEM"  ENABLE
  ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE "SYSTEM";