# Generated by Django 2.2.6 on 2019-11-25 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 34, 27, 157027)),
        ),
    ]
