# Generated by Django 2.2.6 on 2019-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
