# Generated by Django 2.2.6 on 2019-11-25 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0002_auto_20191124_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 35, 15, 993869)),
        ),
    ]
