# Generated by Django 2.2.6 on 2019-11-25 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0003_auto_20191124_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 38, 26, 225716)),
        ),
    ]
