# Generated by Django 2.2.6 on 2019-12-06 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0004_auto_20191124_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 18, 51, 42, 908477)),
        ),
    ]
