# Generated by Django 2.2.6 on 2019-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0005_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
