# Generated by Django 2.2.6 on 2019-12-07 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0005_auto_20191206_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 16, 12, 26, 558139)),
        ),
    ]
