# Generated by Django 2.2.6 on 2019-12-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0006_auto_20191208_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
