# Generated by Django 2.2.5 on 2019-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0008_jokester_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokester',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
