# Generated by Django 2.2.6 on 2019-12-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humorously', '0009_auto_20191209_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
    ]
